### ISSUE TITLE
Text on way rendering

### ISSUE THREAD

**Issue by beelsebob** [beelsebob/OpenStreetPad#9]
Description:
Text on ways can look ugly due to poor letter positioning choices.

Steps to reproduce:
Find a way with a kink in it and a name drawn on it.

Expected results:
The text flows nicely round the corner.

Actual results:
The text collides a lot at the corner, or spaces out, depending on which way the corner bends.

**Comment by Komzpa** [comment]
add max-char-angle-delta (see mapnik docs for explanation) 20-30 degrees is a good unchangeable default.
